version: '3.1'
services:
 nginx:
   image: nginx
   ports:
     - 80:80
   volumes:
     - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
     - /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
 adminer:
   image: adminer

